django_seu/SeuBackend/SeuBackend/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from job.views import job_list,job_detail

urlpatterns = [
    path('', views.home,name='home'), 
    path('admin/', admin.site.urls),  
    path('job/', include('job.urls')),
    
    # path('job/<int:job_id>',job_detail,name='job_detail'),
    # path('job/',job_list,name='job_list'),
]

django_seu/SeuBackend/job/urls.py
from django.urls import path,include
# from job.views import job_detail,job_list   -->  don't need this 
from . import views

# start with job
urlpatterns = [
    # localhost: 8000/job/
    path('',views.job_list,name='job_list'),
    # http://localhost:8000/job/1
    path('<int:job_id>',views.job_detail,name='job_detail'),  # specific article, https://docs.djangoproject.com/en/3.1/ref/urls/
    path('type/<int:job_type_pk>',views.jobs_with_type, name='jobs_with_type'), # <int:job_type_pk> should be same with def jobs_with_type(inputs)
]

django_seu/SeuBackend/polls/urls.py
from django.urls import path

from . import views

# urlpatterns = [
#     # ex: /polls/
#     path('', views.index, name='index'),
#     # ex: /polls/5/
#     # added the word 'specifics'
#     path('specifics/<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

django_seu/SeuBackend/job/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class JobType(models.Model):
    type_name = models.CharField(max_length=50,default='') 
    
    def __str__(self):
        return self.type_name

class Job(models.Model):
    title= models.CharField(max_length=100,default='')
    job_type=models.ForeignKey(JobType, on_delete=models.DO_NOTHING, default='',null=True,blank=True) # ForeignKey to link job_type to JobType
    content=models.TextField(default='')
    author=models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1) # add foreign key to relate auther to user
                                                                            # on_delete: delete job won't delete user
                                                                            # default auther name:1 
    create_time=models.DateTimeField(default=timezone.now)
    # create_time=models.DateTimeField(auto_now_add=True) # same as above
    last_updated_time=models.DateTimeField(auto_now=True) # auto use the time right now
    is_deleted=models.BooleanField(default=False) 
    readed_num=models.IntegerField(default=0)

    def __str__(self):   # show title name on admin
        return '<Job: %s>' % self.title

django_seu/SeuBackend/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
        
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

django_seu/SeuBackend/SeuBackend/views.py
import os
from django.http import HttpResponse
from django.conf import settings
from django.shortcuts import render


def index(request):
    return HttpResponse('Hello World')


def home(request):
    context={ }
    return render(request,'home.html',context)

django_seu/SeuBackend/job/views.py
from django.shortcuts import render,get_object_or_404 # render_to_response
from django.http import HttpResponse, Http404
from .models import Job,JobType

# Create your views here.
##### version 1:
# def job_detail(request,job_id):
#     try:
#         job=Job.objects.get(id=job_id)
#         context={}
#         context['job_obj']=job
#         return render(request,'job_detail.html',context)  # context need to be a dict
#         #return render_to_response('job_detail.html',context)
#     except Job.DoesNotExist:
#         raise Http404('Does Not Exist')

# version 2: 
def job_detail(request,job_id): # specific job->use id
    job=get_object_or_404(Job, pk=job_id) # model(class), requirement: pk=primary key=id
    context={}
    context['job_obj']=job
    return render(request,'job/job_detail.html',context)  # context need to be a dict

def job_list(request):
    # jobs=Job.objects.all()
    jobs=Job.objects.filter(is_deleted=False)  # just show not deleted records
    context={}
    context['jobs']=jobs
    context['jobs_count']=Job.objects.all().count()
    return render(request,'job/job_list.html',context) # context need to be a dict

def jobs_with_type(request,job_type_pk):
    context={} #create dict
    job_type=get_object_or_404(JobType, pk=job_type_pk) # get_object_or_404(model, requirement: pk=(parameter) job_type_pk)
    context['jobs']=Job.objects.filter(job_type=job_type) # object management; 1st job_type is attr of Model Job, 2nd job_type is the variable obtained just now.
    context['job_type']=job_type # for jobs_with_type.html. 
    return render(request, 'job/jobs_with_type.html', context) # come to this page

django_seu/SeuBackend/polls/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponse
from django.template import loader


from django.http import Http404
from .models import Question

# ...


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)


# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

django_seu/SeuBackend/job/templates/job_detail_v1.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <title>{{job.title}}</title>
</head>
<body>
    <div>
        <a href='{% url 'home' %}'> <!--go back to homepage-->
            <h2>SeudoNet Available Job List</h2>
        </a>  
    </div>
  
    <h3>{{job_obj.title}}</h3>  <!--job_obj: from views.py, key of dict, Dictionary lookup'--> 
    <p> Author: {{job_obj.author}}</p>
    <p> Created Time: {{job_obj.create_time  }}</p>
    <p> Category:
        <a href='{% url 'jobs_with_type' job_obj.job_type.pk %}' >
            {{job_obj.job_type}} 
        </a>
    </p>
    <p> {{job_obj.content}}</p>
    
</body>
</html>

django_seu/SeuBackend/job/templates/job_list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <title> SeudoNet Job List</title>
</head>
<body>
    <div>
        <a href='{% url 'home' %}'> <!--go back to homepage-->
            <h2>SeudoNet Available Job List</h2>
        </a>  
    </div>
    <hr>
   
    {% for job in jobs %}  <!--for loop tag-->
        <a href="{% url 'job_detail' job.id %}">  <!--id is primary key to each record-->
            <h3>{{job.title}}</h3>
        </a>
        <p> {{job.content | truncatewords:30}}</p>   <!--|: filter; just show 50 context-->
    {% empty %}  <!--if empty: -->
        <p>--no jobs available right now--</p>
    {% endfor %}
    <p>SeudoNet has {{jobs |length }} jobs available right now</p>
    <!-- {{jobs_count }}    same as {{jobs |length }} -->
</body>
</html>

django_seu/SeuBackend/job/templates/job_list_v1.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <title> SeudoNet Job List</title>
</head>
<body>
    <div>
        <a href='{% url 'home' %}'> <!--go back to homepage-->
            <h2>SeudoNet Available Job List</h2>
        </a>  
    </div>
    <hr>
   
    {% for job in jobs %}  <!--for loop tag-->
        <a href="{% url 'job_detail' job.id %}">  <!--id is primary key to each record-->
            <h3>{{job.title}}</h3>
        </a>
        <p> {{job.content | truncatewords:30}}</p>   <!--|: filter; just show 50 context-->
    {% empty %}  <!--if empty: -->
        <p>--no jobs available right now--</p>
    {% endfor %}
    <p>SeudoNet has {{jobs |length }} jobs available right now</p>
    <!-- {{jobs_count }}    same as {{jobs |length }} -->
</body>
</html>

django_seu/SeuBackend/job/templates/jobs_with_type.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <title> {{job_type.type_name}}</title>  
    <!-- job_type an obstance of class JobType in views.py -->
    <!-- type_name is attr of model JobType -->
</head>
<body>
    <div>
        <a href='{% url 'home' %}'> <!--go back to homepage-->
            <h2>SeudoNet Jobs List</h2>
        </a>  
    </div>
    <hr>
    <h3>{{job_type.type_name}}</h3>  
    <!-- show job type -->

    {% for job in jobs %}  
    <!--for loop tag-->
        <a href="{% url 'job_detail' job.id %}">  
            <!--id is primary key to each record-->
            <h3>{{job.title}}</h3>
        </a>
        <p> {{job.content | truncatewords_html:30}}</p>   
        <!--|: filter; just show 30 words-->
    {% empty %} 
     <!--if empty: -->
        <p>--no jobs available right now--</p>
    {% endfor %}
    <p>SeudoNet has {{jobs |length }} jobs available right now</p>
    <!-- {{jobs_count }}    same as {{jobs |length }} -->
</body>
</html>

django_seu/SeuBackend/job/templates/jobs_with_type_v1.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <title> {{job_type.type_name}}</title>  
    <!-- job_type an obstance of class JobType in views.py -->
    <!-- type_name is attr of model JobType -->
</head>
<body>
    <div>
        <a href='{% url 'home' %}'> <!--go back to homepage-->
            <h2>SeudoNet Jobs List</h2>
        </a>  
    </div>
    <hr>
    <h3>{{job_type.type_name}}</h3>  
    <!-- show job type -->

    {% for job in jobs %}  
    <!--for loop tag-->
        <a href="{% url 'job_detail' job.id %}">  
            <!--id is primary key to each record-->
            <h3>{{job.title}}</h3>
        </a>
        <p> {{job.content | truncatewords_html:30}}</p>   
        <!--|: filter; just show 30 words-->
    {% empty %} 
     <!--if empty: -->
        <p>--no jobs available right now--</p>
    {% endfor %}
    <p>SeudoNet has {{jobs |length }} jobs available right now</p>
    <!-- {{jobs_count }}    same as {{jobs |length }} -->
</body>
</html>

django_seu/SeuBackend/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

django_seu/SeuBackend/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django_seu/SeuBackend/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <title> {% block title %} {% endblock %}</title>  
    <!-- create title block -->
    <link rel="stylesheet" href="/static/base.css"> 
    {% block header %} {% endblock %}

</head>
<body>
    <div class='nav'>
        <a class='logo', href='{% url 'home' %}'> <!--go back to homepage-->
            <h2>SeudoNet Jobs List</h2>
        </a>  
        <a href="/">Homepage</a>
        <a href="{% url 'job_list' %}">Jobs</a>
       
    </div>
    <hr>
    {% block content %}{% endblock %}
    <!-- create content block -->
</body>
</html>

django_seu/SeuBackend/templates/home.html
{% extends 'base.html' %}


{% block title %}
    SeudoNet | Home page
{% endblock %}

{% block header_extends %}
    <link rel="stylesheet" href="/static/home.css">
{% endblock %}

{% block content %}
    <h3 class="home-content">Welcome to SeudoNet</h3>
{% endblock %}

django_seu/SeuBackend/templates/job/job_detail.html
{% extends 'base.html'%}

{# title #}
{% block title %} 
    {{job.title}}
{% endblock %}

{# content #}
{% block content %}
<h3>{{job_obj.title}}</h3>  <!--job_obj: from views.py, key of dict, Dictionary lookup'--> 
<p> Author: {{job_obj.author}}</p>
<p> Created Time: {{job_obj.create_time}}</p>
<p> Category:
    <a href='{% url 'jobs_with_type' job_obj.job_type.pk %}' >
        {{job_obj.job_type}} 
    </a>
</p>
<p> {{job_obj.content}}</p>
{% endblock %}

django_seu/SeuBackend/templates/job/job_list.html
{% extends 'base.html'%}

{# title #}
{% block title %} 
    SeudoNet Job List
{% endblock %}

{# content #}
{% block content %}
    {% for job in jobs %}  <!--for loop tag-->
        <a href="{% url 'job_detail' job.id %}">  <!--id is primary key to each record-->
            <h3>{{job.title}}</h3>
        </a>
        <p> {{job.content | truncatewords:30}}</p>   <!--|: filter; just show 50 context-->
    {% empty %}  <!--if empty: -->
        <p>--no jobs available right now--</p>
    {% endfor %}
    <p>SeudoNet has {{jobs |length }} jobs available right now</p>
    <!-- {{jobs_count }}    same as {{jobs |length }} -->
{% endblock %}

django_seu/SeuBackend/templates/job/jobs_with_type.html
{% extends 'base.html' %}

{% block title %}
    {{job_type.type_name}}
    <!-- job_type an obstance of class JobType in views.py -->
    <!-- type_name is attr of model JobType -->
{% endblock%} 

{% block content%}

    {% for job in jobs %}  
    <!--for loop tag-->
        <a href="{% url 'job_detail' job.id %}">  
            <!--id is primary key to each record-->
            <h3>{{job.title}}</h3>
        </a>
        <p> {{job.content | truncatewords_html:30}}</p>   
        <!--|: filter; just show 30 words-->
    {% empty %} 
     <!--if empty: -->
        <p>--no jobs available right now--</p>
    {% endfor %}
    <p>SeudoNet has {{jobs |length }} jobs available right now</p>
    <!-- {{jobs_count }}    same as {{jobs |length }} -->
{% endblock%}